### PR TITLE
fix: unable to click x tray

### PR DESCRIPTION
**Pull request by tsic404**
update tray raw global pos

log: as title

### CODE REVIEW

**Review by 18202781743 — APPROVED** [review]

**Comment by 18202781743** [comment]
https://github.com/linuxdeepin/developer-center/issues/9648

**Comment by tsic404** [comment]
> [linuxdeepin/developer-center#9648](https://github.com/linuxdeepin/developer-center/issues/9648)

和层级应该无关

**Comment by tsic404** [comment]
issue: https://github.com/linuxdeepin/developer-center/issues/9968

**Pull request merged**
